### ISSUE TITLE
Todo for Bodong's class

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1404]
- [ ] external access to LIs outside of graphs
- [x] map external artefacts to students based on userids
- [x] polish hypothesis LI a bit
- [x] add date to hypothesis query
- [x] make text areas larger?
