### ISSUE TITLE
Tracking tech development required for Valerie's class

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#255]
We should begin tracking the tech development that will be required for the UNIL run. Apart from general stability, etc.

Key issues that have not been decided yet?
- [ ] Desktop or mobile or both? We have gone back and forth, most recent was desktop. This is a very important decision in terms of the whole script design
- [ ] How to manage student login/identity etc, whether to login from Moodle, have anonymous, etc.

Things we know we'll need: 
- [ ] Support for external operators (Kshitij classification). Does it need to run incrementally?

**Comment by thanasishadzilacos** [comment]
(I suppose you mean 'laptop', not 'desktop', right?)
**For** laptop: Easier to type; easier to work in groups; FROG is already being developed for laptop (right?)
**Against** laptop: Not everybody will bring their laptop; students need to be reminded and they might not bring them
**For** mobile: Practically everybody has one with them all the time
**Against** mobile: More difficult interaction; more difficult to share screen; more development for FROG needed
**For** both: combines advantages for students; will have FROG working for both in the future
**Against** both: more development work without additional functionality; more risk of delay/failure; will have to sacrifice other functionality
Θανάσης conclusion: Go for laptop only; reconsider after the experiment is over.

Managing student login/identity. Before we evaluate and decide, we must clarify the options:
Students register to FROG using 
Option 1 - Moodle: their UNIL Student Moodle ID
Option 2 - a username of their choice and an email (not necessarily UNIL email) that FROG can verify (sends a link to the email address to be clicked before the student FROG account is activated)
Option 3 - a username of their choice so long as it is unique. No other check is performed by FROG.
Any other options?

Where is Kshitij classification for external operators?
