### ISSUE TITLE
Checklist for stroop effect experiment

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#821]
We need to do 

- [x] Hardcode questions, keeping track of avoiding ambiguous colors (brown lemon), and not repeating (Stian)
- [x] Format of sentence is ugly on the first screen (Louis)
- [x] Fix leaderboard names and change to relative start time instead of absolute (Louis)
- [x] Have language picker (Louis)
- [x] Have the personalization screen in Stroop (Louis)
- [x] Fix react-modal (Stian)
- [x] Change progress graph axis to "Average class progress" (Jenny)
- [x] Have line showing how many students have completed it in the progress (Jenny)
- [x] Remove blue dots on progress graph (Jenny)
- [x] change configuration of 1 sec delay and 3 sec timing (Jenny)
- [x] Fix progress line graph #823 
- [x] Set up production infrastructure 
- [ ] stress-test (Stian)
- [ ] re-enable Sentry (Stian)

Future
- [ ] Enable teacher to move back in graph?
