### ISSUE TITLE
TODO before Boston

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#92]
## TODO
- [ ] -> Have a User module which is called instead of Meteor.loggedInUser (maybe use MobX?)
- [ ] -> Parse user from URL and implement user logging in through for example /#graph?user=Stian
- [ ] -> Script for the demo (Stian)
- [ ] -> Technical implementation of simulation for the demo (Stian) 

## BONUS
- [ ] -> Word cloud / differential word cloud dashboard (Louis, bonus)
- [ ] -> Read only version of the graph with a progress bar for teacher orchestration and visualization of students groups (any) (Stian, very bonus)
