### ISSUE TITLE
CS211 TODO List

### ISSUE THREAD

**Issue by jkolsen** [chili-epfl/FROG#927]
- [x] Train Activity (Prastut)
- [x] Train Activity Dashboards (Prastut, Jenny)
- [x] Product operator for assigning students different prompts in the same activity (Stian)
- [x] Implement ac-ranking: Select and reorder quiz (Jenny)
- [x] Make ac-ranking collaborative (Stian, Jenny)
- [x] Algorithm to get coordinates from ranking within ac-ranking (Louis)
- [x] Social operator for pairing students based on rankings with constraints (Louis)
- [x] Product operator for aggregating individual answers to the pair activity (Stian)
- [x] Allow more than one input into a product operator (Stian)
- [x] Product operator that outputs the groups/students that changed answers and maybe graphs? (Stian)
- [x] Optimize back-end processing of dashboards (Stian)
- [ ] Add multi-server support to new dashboard approach (Stian)
- [x] Update progress dashboard (Stian, Louis, Jenny, Jiaxi)
- [x] Add names on argue scatter plot (Louis)

------Changes after Pierre meeting-------------
Train
- [x] Buy and help buttons changed to say "Buy" and "Help" on train activity
- [x] Error message should say "Wrong ticket purchased" and "Correct ticket purchased"
- [x] Completion bar needs to be larger and have a completion percentage
- [x] Be able to hit return/enter to buy a ticket
- [x] Have more feedback on the map when something is clickable and do not have them click first in the from and to boxes (or automatic selection)
- [x] Change graph wording from "per try" to "per ticket"

Ranking (Jenny will do these)
- [x] On original buttons do not have the numbering and add a sentence instead
- [x] On the coordinate graph, label the four interfaces
- [x] Ranking prompts are "If you rarely buy a train ticket rank the interfaces in the order that you would most prefer them." and "If you work for the train company, rank the interfaces in the order that you would most prefer them." and "Rank the interfaces in the order that you would most prefer them."
- [x] Show a picture of the four interfaces

Prediction algorithm (Jiaxi)
- [x] Optimize algorithm 
- [x] Revise data structure for better computational performance
- [x] Make sure ac-train sends a log when progress is 0

Misc
- [ ] Want a graph showing the correlation between performance and preference
- [x] Matrix table of the transforms of first preference from individual to group and group to group with data
- [x] only 4 tries
- [x] have consent between individual and group preference

**Comment by lfaucon** [comment]
EDITS:
- "Drag and drop" -> "Implement ac-ranking: Select and reorder quiz"
As discussed 
- "Product operator for getting coordinates from ranking" -> "Algorithm to get coordinates from ranking within ac-ranking"
Actually if we want the coordinates on a dashboard, we've got to make this coordinates in the activity

**Comment by lfaucon** [comment]
EDITS:
- adding "Add names on argue scatter plot"

**Comment by jkolsen** [comment]
If there are any things for this experiment that you are working on that are not on the list, feel free to edit it just so we can track progress.

**Comment by Jiaxigu** [comment]
added some TODOs regarding the predictions before the upcoming experiment.

**Comment by lfaucon** [comment]
To be continued in #1071
